name: Tests
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24
      - run: npm ci
      - run: npm test
